<?php

namespace ContainerVxfkEmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerreadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._xxDIzo.App\Controller\HomeController::read()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._xxDIzo.App\\Controller\\HomeController::read()'] = ($container->privates['.service_locator._xxDIzo'] ?? $container->load('get_ServiceLocator_XxDIzoService'))->withContext('App\\Controller\\HomeController::read()', $container);
    }
}
