<?php

namespace Container6fr2tby;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GPBqT6TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GPBqT6T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GPBqT6T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\HomeController::signin' => ['privates', '.service_locator.r_XOrDH.App\\Controller\\HomeController::signin()', 'getHomeControllersigninService', true],
            'App\\Controller\\HomeController::create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\HomeController::create()', 'getHomeControllercreateService', true],
            'App\\Controller\\HomeController::update' => ['privates', '.service_locator._xxDIzo.App\\Controller\\HomeController::update()', 'getHomeControllerupdateService', true],
            'App\\Controller\\HomeController::read' => ['privates', '.service_locator._xxDIzo.App\\Controller\\HomeController::read()', 'getHomeControllerreadService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\HomeController:signin' => ['privates', '.service_locator.r_XOrDH.App\\Controller\\HomeController::signin()', 'getHomeControllersigninService', true],
            'App\\Controller\\HomeController:create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\HomeController::create()', 'getHomeControllercreateService', true],
            'App\\Controller\\HomeController:update' => ['privates', '.service_locator._xxDIzo.App\\Controller\\HomeController::update()', 'getHomeControllerupdateService', true],
            'App\\Controller\\HomeController:read' => ['privates', '.service_locator._xxDIzo.App\\Controller\\HomeController::read()', 'getHomeControllerreadService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::signin' => '?',
            'App\\Controller\\HomeController::create' => '?',
            'App\\Controller\\HomeController::update' => '?',
            'App\\Controller\\HomeController::read' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:signin' => '?',
            'App\\Controller\\HomeController:create' => '?',
            'App\\Controller\\HomeController:update' => '?',
            'App\\Controller\\HomeController:read' => '?',
        ]);
    }
}
