<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQKjgwZN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQKjgwZN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQKjgwZN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQKjgwZN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQKjgwZN\App_KernelDevDebugContainer([
    'container.build_hash' => 'QKjgwZN',
    'container.build_id' => '86d174c7',
    'container.build_time' => 1731358023,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQKjgwZN');
