<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container64Doj04\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container64Doj04/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container64Doj04.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container64Doj04\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container64Doj04\App_KernelDevDebugContainer([
    'container.build_hash' => '64Doj04',
    'container.build_id' => 'abe68eb6',
    'container.build_time' => 1731338049,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container64Doj04');
