<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6fr2tby\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6fr2tby/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6fr2tby.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6fr2tby\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6fr2tby\App_KernelDevDebugContainer([
    'container.build_hash' => '6fr2tby',
    'container.build_id' => 'f75e3bc8',
    'container.build_time' => 1731334267,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6fr2tby');
